In [39]:
import numpy as np
import pandas as pd
import tensorflow as tf
import csv
import torch as th
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
import torch.optim as optim
from torch.utils.data import DataLoader

In [ ]:
tf.__version__

'2.13.0'

In [ ]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [ ]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])

In [ ]:
print(X)

[[ 19   4]
 [ 35   5]
 [ 26  26]
 [ 27  39]
 [ 19  57]
 [ 27  40]
 [ 27  65]
 [ 32 116]
 [ 25  17]
 [ 35  47]
 [ 26  61]
 [ 26  35]
 [ 20  67]
 [ 32   3]
 [ 18  63]
 [ 29  61]
 [ 47   9]
 [ 45  10]
 [ 46  12]
 [ 48  13]
 [ 45   7]
 [ 47  32]
 [ 48  24]
 [ 45   7]
 [ 46   8]
 [ 47   5]
 [ 49  12]
 [ 47  14]
 [ 29  26]
 [ 31   3]
 [ 31  55]
 [ 27 105]
 [ 21   1]
 [ 28  27]
 [ 27  71]
 [ 35  11]
 [ 33  12]
 [ 30  32]
 [ 26  53]
 [ 27  15]
 [ 27   2]
 [ 33  34]
 [ 35  85]
 [ 30   0]
 [ 28  65]
 [ 23   5]
 [ 25  60]
 [ 27  37]
 [ 30 104]
 [ 31  70]
 [ 24  16]
 [ 18  27]
 [ 29  64]
 [ 35   8]
 [ 27  40]
 [ 24  38]
 [ 23  31]
 [ 28  60]
 [ 22   3]
 [ 32  91]
 [ 27   5]
 [ 25  68]
 [ 23  48]
 [ 32  94]
 [ 59  64]
 [ 24  40]
 [ 24   4]
 [ 23  63]
 [ 22  45]
 [ 31  49]
 [ 25  61]
 [ 24  11]
 [ 20   8]
 [ 33  87]
 [ 32   3]
 [ 34  86]
 [ 18  35]
 [ 22  11]
 [ 28  68]
 [ 26   2]
 [ 30  61]
 [ 39  25]
 [ 20  32]
 [ 35  69]
 [ 30  44]
 [ 31  92]
 [ 24  38]
 [ 28  66]
 [ 26  62]
 [ 35  33]
 [ 22  62]

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

  (0, 4)	1.0
  (0, 117)	19.0
  (1, 5)	1.0
  (1, 117)	35.0
  (2, 26)	1.0
  (2, 117)	26.0
  (3, 39)	1.0
  (3, 117)	27.0
  (4, 57)	1.0
  (4, 117)	19.0
  (5, 40)	1.0
  (5, 117)	27.0
  (6, 65)	1.0
  (6, 117)	27.0
  (7, 116)	1.0
  (7, 117)	32.0
  (8, 17)	1.0
  (8, 117)	25.0
  (9, 47)	1.0
  (9, 117)	35.0
  (10, 61)	1.0
  (10, 117)	26.0
  (11, 35)	1.0
  (11, 117)	26.0
  (12, 67)	1.0
  :	:
  (387, 117)	39.0
  (388, 18)	1.0
  (388, 117)	47.0
  (389, 19)	1.0
  (389, 117)	48.0
  (390, 17)	1.0
  (390, 117)	48.0
  (391, 8)	1.0
  (391, 117)	47.0
  (392, 28)	1.0
  (392, 117)	45.0
  (393, 25)	1.0
  (393, 117)	60.0
  (394, 41)	1.0
  (394, 117)	39.0
  (395, 24)	1.0
  (395, 117)	46.0
  (396, 8)	1.0
  (396, 117)	51.0
  (397, 5)	1.0
  (397, 117)	50.0
  (398, 17)	1.0
  (398, 117)	36.0
  (399, 20)	1.0
  (399, 117)	49.0


In [38]:
targets_numpy = dataset.Purchased.values
features_numpy = dataset.loc[:,dataset.columns != "Purchased"].values

features_train, features_test, targets_train, targets_test = train_test_split(features_numpy,targets_numpy,test_size = 0.2,random_state = 42)
X_train = th.from_numpy(features_train).type(th.FloatTensor)
y_train = th.from_numpy(targets_train).type(th.FloatTensor)

X_test = th.from_numpy(features_test).type(th.FloatTensor)
y_test = th.from_numpy(targets_test).type(th.FloatTensor)

train = th.utils.data.TensorDataset(X_train, Y_train)
test = th.utils.data.TensorDataset(X_test, Y_test)

batch_size = 20

from torch.utils.data import random_split

train_set, val_set = random_split(train, [220, 100])

train_loader = DataLoader(train_set, batch_size = batch_size, shuffle = True)
val_loader = DataLoader(val_set, batch_size = batch_size, shuffle = True)
test_loader = DataLoader(test, batch_size = batch_size, shuffle = False)

NameError: ignored

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [41]:
ann = tf.keras.models.Sequential()

In [42]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [43]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [44]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [45]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [46]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

TypeError: ignored

In [47]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

ValueError: ignored

In [48]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

3/3 [==============================] - 0s 5ms/step
[[1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [0. 1.]
 [1. 0.]
 [1. 1.]
 [0. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 0.]
 [1. 0.]
 [0. 1.]
 [0. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [1. 0.]
 [0. 1.]
 [1. 1.]
 [1. 0.]
 [0. 1.]]


In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 8 44]
 [18 10]]


0.225